import Link from "next/link";
import { ArrowRight, Play, ShieldCheck } from "lucide-react";
import { CloudScene, LogoMarquee, TrustedGrid } from "@/components/brand/logos";
import { FaqList } from "@/components/home/faq-list";
import { ButtonLink } from "@/components/ui/button";
import { Container } from "@/components/ui/container";

const posts = [
  {
    name: "Thomas Higadère",
    role: "Creator · B2B & AI · 34K followers",
    title: "How AI changed our prospecting workflow for wealth managers and private bankers.",
    impressions: "42.8K",
    clicks: "312",
    leads: "18",
    brand: "lemlist",
    brandLogo: "/lp/logo-lemlist.png",
    image: "/lp/marketplace-atmosphere-v1.png",
    avatar: "/lp/avatar-a.png",
  },
  {
    name: "Robin Tempe",
    role: "Creator · Sales & AI · 12K followers",
    title: "I run my entire prospecting workflow through an AI. Here is how.",
    impressions: "9K",
    clicks: "100",
    leads: "50",
    brand: "Leadbay",
    brandLogo: "/lp/logo-leadbay.png",
    image: "/lp/journey-cloud-current-v1.png",
    avatar: "/lp/avatar-b.png",
  },
  {
    name: "Eric Djavid",
    role: "Sales Leader · B2B · 40K followers",
    title: "Most sales teams spend 80% of their time on the wrong leads. Here is how I changed that.",
    impressions: "20K",
    clicks: "350",
    leads: "80",
    brand: "Leadbay",
    brandLogo: "/lp/logo-leadbay.png",
    image: "/lp/marketplace-screenshot-clean-v2.png",
    avatar: "/lp/avatar-c.png",
  },
  {
    name: "Marina Panova",
    role: "Content Creator · B2B · 34K followers",
    title: "How I build my 30-day LinkedIn content system, the exact playbook.",
    impressions: "100K",
    clicks: "1,600",
    leads: "320",
    brand: "Abyssale",
    brandLogo: "/lp/logo-abyssale.png",
    image: "/lp/results-metrics-clouds-v2.png",
    avatar: "/lp/avatar-d.png",
  },
];

function XIcon() {
  return (
    <svg viewBox="0 0 16 16" className="size-3.5" aria-hidden>
      <path fill="currentColor" d="M12.6 1.5h2.2L9.7 7.2 16 14.5h-4.7L7.6 9.8 3.3 14.5H1.1l7.5-6.2L0 1.5h4.8l3.6 4.3 4.2-4.3Zm-.8 11.7h1.2L4.3 2.7H3L11.8 13.2Z" />
    </svg>
  );
}

function InIcon() {
  return (
    <svg viewBox="0 0 16 16" className="size-3.5 text-[#0a66c2]" aria-hidden>
      <path fill="currentColor" d="M14.7 0H1.3C.6 0 0 .6 0 1.3v13.4C0 15.4.6 16 1.3 16h13.4c.7 0 1.3-.6 1.3-1.3V1.3C16 .6 15.4 0 14.7 0ZM4.7 13.6H2.4V6h2.3v7.6ZM3.6 5C2.8 5 2.2 4.4 2.2 3.6S2.8 2.2 3.6 2.2 5 2.8 5 3.6 4.3 5 3.6 5Zm10 8.6h-2.3V9.9c0-.9 0-2-1.2-2s-1.4 1-1.4 2v3.7H6.4V6h2.2v1c.3-.6 1.1-1.2 2.2-1.2 2.4 0 2.8 1.6 2.8 3.6v4.2Z" />
    </svg>
  );
}

export function HomePage() {
  return (
    <>
      <CloudScene className="-mt-[72px] flex min-h-[100svh] flex-col pb-24 pt-[108px]">
        <Container className="relative flex flex-1 flex-col items-center justify-center text-center">
          <span className="inline-flex items-center gap-2 rounded-full border border-white/80 bg-white/70 px-3.5 py-1.5 text-[13px] text-ink/70 shadow-sm backdrop-blur-sm">
            <XIcon />
            <InIcon />
            Where B2B brands work with creators
          </span>
          <h1 className="display mx-auto mt-7 max-w-5xl text-[44px] sm:text-[62px] lg:text-[76px]">
            The B2B LinkedIn
            <br />
            Creator Marketplace.
          </h1>
          <p className="mx-auto mt-6 max-w-[640px] text-[17px] leading-7 text-ink/60">
            Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.
          </p>
          <div className="mt-9 flex flex-wrap items-center justify-center gap-6">
            <ButtonLink href="/register?role=saas" size="lg" className="h-12 bg-[#17181C] px-6 text-[15px]">
              Launch a campaign
              <ArrowRight className="size-4" />
            </ButtonLink>
            <Link href="/#how-it-works" className="inline-flex items-center gap-1 text-[15px] font-medium text-ink">
              See how Naano works <ArrowRight className="size-4" />
            </Link>
          </div>
          <p className="mt-8 inline-flex items-center gap-2 text-[13px] text-ink/45">
            <ShieldCheck className="size-4" /> Trusted by modern B2B teams
          </p>
        </Container>
        <div className="mt-12">
          <LogoMarquee caseStudy />
        </div>
      </CloudScene>

      <section className="bg-white py-24 text-center">
        <Container>
          <img src="/lp/logo-zmirov.png" alt="zmirov communication" className="mx-auto h-12 w-auto object-contain" />
          <blockquote className="display mx-auto mt-8 max-w-3xl text-[34px] leading-[1.15] sm:text-[42px]">
            “We manage €10M+ of influence budget every year. For B2B,{" "}
            <span className="text-ink/25">Naano simply makes our life</span>{" "}
            <span className="bg-gradient-to-r from-ink/40 to-sky bg-clip-text text-transparent">easier</span>”
          </blockquote>
          <div className="mt-10">
            <img src="/lp/avatar-e.png" alt="David Zmirov" className="mx-auto size-16 rounded-full object-cover" />
            <p className="mt-3 font-medium">David Zmirov</p>
            <p className="text-sm text-muted">CEO, Zmirov Communication</p>
            <p className="text-xs text-muted">Influence agency</p>
          </div>
        </Container>
      </section>

      <section className="relative overflow-hidden bg-gradient-to-b from-white via-[#eaf6fd] to-white pb-8 pt-10">
        <Container className="relative z-10 text-center">
          <span className="inline-flex items-center gap-2 rounded-full bg-white/80 px-3 py-1 text-xs text-brand">
            <span className="size-1.5 rounded-full bg-brand" />
            The Naano creator marketplace
          </span>
          <h2 className="display mx-auto mt-5 max-w-3xl text-[40px] sm:text-[52px]">
            Work with all the best
            <br />
            creators.
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-[16px] text-ink/60">
            Find the right B2B voices, compare their audience fit, and book every collaboration from one place.
          </p>
        </Container>
        <div className="relative mx-auto mt-10 max-w-[1120px] px-4">
          <div className="overflow-hidden rounded-[28px] border border-white/80 bg-white/80 p-3 shadow-[0_40px_90px_-50px_rgb(23_24_28/0.55)]">
            <div className="mb-3 flex items-center justify-center">
              <span className="rounded-full bg-white px-4 py-1 text-[12px] text-ink/40 shadow-sm">naano.co/marketplace</span>
            </div>
            <img src="/lp/marketplace-screenshot-clean-v2.png" alt="Naano marketplace showing a curated selection of B2B creators" className="w-full rounded-2xl" />
          </div>
        </div>
      </section>

      <section className="bg-gradient-to-b from-[#eaf6fd] to-white py-10">
        <Container>
          <div className="grid gap-4 md:grid-cols-3">
            <article className="rounded-[28px] bg-white p-6 shadow-[0_16px_50px_-40px_rgb(23_24_28/0.5)]">
              <div className="flex -space-x-2">
                {["a", "b", "c", "d", "e"].map((id) => (
                  <img key={id} src={`/lp/avatar-${id}.png`} alt="" className="size-10 rounded-full border-2 border-white object-cover" />
                ))}
              </div>
              <h3 className="mt-8 text-lg font-semibold">3,000+ vetted creators</h3>
              <p className="mt-1 text-sm text-muted">Specialist B2B voices, ready to collaborate.</p>
            </article>
            <article className="rounded-[28px] bg-white p-6 shadow-[0_16px_50px_-40px_rgb(23_24_28/0.5)]">
              <p className="flex flex-wrap gap-2 text-2xl">🇫🇷 🇺🇸 🇩🇪 🇬🇧 🇪🇸 🇨🇦 🇳🇱</p>
              <h3 className="mt-10 text-lg font-semibold">Across 100 countries</h3>
              <p className="mt-1 text-sm text-muted">Local expertise with genuinely global reach.</p>
            </article>
            <article className="rounded-[28px] bg-white p-6 shadow-[0_16px_50px_-40px_rgb(23_24_28/0.5)]">
              <div className="flex items-center justify-between">
                <div>
                  <img src="/lp/avatar-f.png" alt="" className="size-14 rounded-full object-cover" />
                  <p className="mt-2 text-xs text-muted">AI & SaaS creator</p>
                </div>
                <div className="text-right">
                  <p className="text-3xl font-semibold text-brand">96%</p>
                  <div className="mt-2 space-y-1 text-left text-[11px] text-ink/60">
                    <p className="rounded-full bg-surface px-2 py-1">Founders</p>
                    <p className="rounded-full bg-surface px-2 py-1">Sales leaders</p>
                    <p className="rounded-full bg-surface px-2 py-1">GTM teams</p>
                  </div>
                </div>
              </div>
              <h3 className="mt-6 text-lg font-semibold">Matched to your buyers</h3>
              <p className="mt-1 text-sm text-muted">Audience fit comes before follower count.</p>
            </article>
          </div>
        </Container>
      </section>

      <section id="how-it-works" className="bg-white pb-8 pt-16">
        <Container>
          <p className="text-[11px] font-semibold tracking-[0.16em] text-ink/40">
            <span className="mr-2 inline-block size-1.5 rounded-full bg-brand align-middle" />
            ONE PLATFORM, FROM BRIEF TO RESULTS
          </p>
          <div className="mt-4 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
            <h2 className="display max-w-xl text-[40px] sm:text-[48px]">
              Run creator campaigns
              <br />
              from one place.
            </h2>
            <p className="max-w-sm text-[15px] text-ink/55">
              Find the right voices, launch faster, and connect every post to measurable business results.
            </p>
          </div>
          <div className="mt-12 grid gap-3 md:grid-cols-5">
            {[
              { n: "01", title: "Find creators your buyers trust", body: "Eric, Robin and Aya scored on audience fit." },
              { n: "02", title: "Build a campaign brief in minutes", body: "Objectives, guidelines and tracking links." },
              { n: "03", title: "Manage every collaboration", body: "Draft ready, scheduled, live." },
              { n: "04", title: "Track reach, clicks, and leads", body: "€48.2K attributed pipeline." },
              { n: "05", title: "Pay creators without the admin", body: "Contract, invoice, payout handled by Naano." },
            ].map((step) => (
              <div key={step.n} className="rounded-[28px] bg-[#f6f8fb] p-5">
                <p className="text-[12px] text-muted">{step.n}</p>
                <div className="my-8 h-24 rounded-2xl bg-white/80" />
                <p className="text-[16px] font-medium leading-snug">{step.title}</p>
              </div>
            ))}
          </div>
        </Container>
      </section>

      <section className="bg-white py-20">
        <Container>
          <h2 className="display text-[40px] sm:text-[48px]">Real teams. Measurable pipeline.</h2>
          <p className="mt-3 max-w-xl text-[16px] text-ink/55">
            See how B2B teams turn creator trust into attributable demand with Naano.
          </p>
          <div className="mt-10 grid overflow-hidden rounded-[32px] bg-[#f6f8fb] lg:grid-cols-[0.9fr_1.1fr]">
            <div className="p-5">
              <p className="mb-3 text-[11px] tracking-[0.16em] text-ink/40">VIDEO TESTIMONIAL</p>
              <div className="relative overflow-hidden rounded-3xl">
                <img src="/lp/blogseo-vincent-video-poster.png" alt="Vincent Josse, BlogSEO" className="h-72 w-full object-cover" />
                <span className="absolute left-1/2 top-1/2 grid size-14 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white/90">
                  <Play className="size-6 fill-ink text-ink" />
                </span>
                <span className="absolute bottom-3 right-3 rounded-full bg-black/55 px-2 py-0.5 text-[11px] text-white">2:40</span>
              </div>
              <p className="mt-5 text-[22px] font-semibold leading-snug">
                “Naano became one of our fastest acquisition channels. We know exactly what every creator brings.”
              </p>
              <div className="mt-4 flex items-center gap-3 rounded-full bg-white px-3 py-2">
                <img src="/lp/avatar-g.png" alt="" className="size-9 rounded-full object-cover" />
                <div>
                  <p className="text-sm font-medium">Vincent Josse</p>
                  <p className="text-xs text-muted">CEO & Founder, BlogSEO</p>
                </div>
              </div>
            </div>
            <div className="p-8">
              <div className="flex items-center justify-between">
                <p className="text-[11px] font-semibold tracking-[0.16em] text-muted">CASE STUDY</p>
                <img src="/lp/logo-blogseo.png" alt="BlogSEO" className="h-6 w-auto" />
              </div>
              <h3 className="mt-4 text-[28px] font-semibold leading-tight">How BlogSEO turned creator content into product signups</h3>
              <p className="mt-3 text-sm leading-6 text-ink/60">
                BlogSEO briefed SEO & SaaS creators on LinkedIn and X, then traced every trial back to the post that drove it, all in Naano.
              </p>
              <div className="mt-8 grid grid-cols-3 gap-3 text-left">
                <div>
                  <p className="text-3xl font-semibold">9</p>
                  <p className="text-xs text-muted">creators activated</p>
                </div>
                <div>
                  <p className="text-3xl font-semibold">2,940</p>
                  <p className="text-xs text-muted">qualified clicks</p>
                </div>
                <div>
                  <p className="text-3xl font-semibold">512</p>
                  <p className="text-xs text-muted">trials started</p>
                </div>
              </div>
              <Link href="/case-studies/blogseo" className="mt-6 inline-flex items-center gap-1 text-sm font-medium">
                Read case study <ArrowRight className="size-4" />
              </Link>
              <div className="mt-8 border-t border-border pt-6">
                <p className="text-[11px] tracking-[0.16em] text-muted">TRUSTED BY TEAMS AT</p>
                <div className="mt-4">
                  <TrustedGrid />
                </div>
                <span className="mt-4 inline-flex rounded-full border border-border px-3 py-1 text-xs text-muted">+30</span>
              </div>
            </div>
          </div>
        </Container>
      </section>

      <section className="relative overflow-hidden py-16">
        <img src="/lp/results-metrics-clouds-v2.png" alt="" className="pointer-events-none absolute inset-0 h-full w-full object-cover opacity-80" />
        <Container className="relative">
          <p className="text-center text-[11px] font-semibold tracking-[0.16em] text-ink/45">
            <span className="mr-2 inline-block size-1.5 rounded-full bg-brand align-middle" />
            THE RESULTS
          </p>
          <h2 className="display mt-3 text-center text-[40px] sm:text-[48px]">Proven across thousands of campaigns.</h2>
          <div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-4">
            {[
              ["5M+", "Impressions generated"],
              ["30K+", "Leads generated"],
              ["2,000+", "Creators on Naano"],
              ["5K+", "Posts published"],
            ].map(([value, label]) => (
              <div key={label} className="rounded-[28px] bg-white/80 px-4 py-8 text-center backdrop-blur">
                <p className="text-4xl font-semibold">{value}</p>
                <p className="mt-1 text-sm text-muted">{label}</p>
              </div>
            ))}
          </div>
          <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            {posts.map((post) => (
              <article key={post.name} className="overflow-hidden rounded-[28px] bg-white p-4 shadow-[0_16px_50px_-40px_rgb(23_24_28/0.45)]">
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <img src={post.avatar} alt="" className="size-9 rounded-full object-cover" />
                    <div>
                      <p className="text-sm font-semibold">{post.name}</p>
                      <p className="text-[11px] text-muted">{post.role}</p>
                    </div>
                  </div>
                  <InIcon />
                </div>
                <p className="mt-4 text-[15px] font-medium leading-snug">{post.title}</p>
                <img src={post.image} alt="" className="mt-4 h-32 w-full rounded-2xl object-cover" />
                <div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs">
                  <div>
                    <p className="font-semibold">{post.impressions}</p>
                    <p className="text-muted">Impressions</p>
                  </div>
                  <div>
                    <p className="font-semibold">{post.clicks}</p>
                    <p className="text-muted">Clicks</p>
                  </div>
                  <div>
                    <p className="font-semibold">{post.leads}</p>
                    <p className="text-muted">Leads</p>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between text-xs">
                  <span className="inline-flex items-center gap-1 text-muted">
                    For <img src={post.brandLogo} alt={post.brand} className="h-4 w-auto" />
                  </span>
                  <Link href="/register" className="font-medium text-brand">
                    View post ↗
                  </Link>
                </div>
              </article>
            ))}
          </div>
          <div className="mt-10 text-center">
            <ButtonLink href="/register" size="lg" className="h-12 bg-[#17181C] px-7">
              Get started <ArrowRight className="size-4" />
            </ButtonLink>
            <p className="mt-3 text-sm text-muted">Start free. Pay per post when you&apos;re ready.</p>
          </div>
        </Container>
      </section>

      <section id="pricing" className="bg-white py-20">
        <Container>
          <h2 className="display text-[52px]">Pricing.</h2>
          <p className="mt-3 max-w-xl text-[18px] font-medium">Start free. Upgrade when you want your time back.</p>
          <p className="mt-2 max-w-xl text-sm text-muted">
            Choose whether you want to run creator campaigns in-house or have Naano operate them.
          </p>
          <div className="mt-10 grid gap-4 lg:grid-cols-2">
            <div className="rounded-[32px] border border-border p-8">
              <p className="text-[11px] font-semibold tracking-[0.16em] text-muted">SELF-SERVE</p>
              <h3 className="mt-4 text-[32px] font-semibold">Run it yourself.</h3>
              <p className="mt-3 max-w-sm text-sm text-muted">For teams that want the infrastructure to run creator campaigns in-house.</p>
              <p className="mt-8 text-5xl font-semibold">
                €0 <span className="text-base font-normal text-muted">/ month</span>
              </p>
              <ul className="mt-8 divide-y divide-border text-[15px]">
                {["Creator marketplace access", "AI-powered brief creation", "Track clicks, companies and pipeline", "Automatic creator payouts"].map((item) => (
                  <li key={item} className="py-4">
                    {item}
                  </li>
                ))}
              </ul>
              <Link href="/register" className="mt-4 inline-flex items-center gap-1 font-medium underline-offset-4 hover:underline">
                Start for free <ArrowRight className="size-4" />
              </Link>
            </div>
            <div className="rounded-[32px] border border-border p-8">
              <p className="text-[11px] font-semibold tracking-[0.16em] text-brand/80">MANAGED CAMPAIGNS</p>
              <h3 className="mt-4 text-[32px] font-semibold">Get your time back.</h3>
              <p className="mt-3 max-w-sm text-sm text-muted">For teams that want Naano to operate their creator channel end to end.</p>
              <p className="mt-8 text-5xl font-semibold">Custom quote</p>
              <ul className="mt-8 divide-y divide-border text-[15px]">
                {["Campaign strategy and positioning", "Creator sourcing and coordination", "Brief creation and campaign launch", "Reporting and optimisation"].map((item) => (
                  <li key={item} className="py-4">
                    {item}
                  </li>
                ))}
              </ul>
              <ButtonLink href="/book" className="mt-4 h-12 w-full max-w-xs bg-[#17181C]">
                Book a campaign call <ArrowRight className="size-4" />
              </ButtonLink>
            </div>
          </div>
          <p className="mt-6 inline-flex items-center gap-2 text-sm text-muted">
            <ShieldCheck className="size-4" /> Campaign spend is separate. No lock-in. Cancel anytime.
          </p>
        </Container>
      </section>

      <section id="faq" className="bg-white py-16">
        <Container className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr]">
          <div>
            <h2 className="display text-[44px] leading-[1.05]">
              Frequently
              <br />
              asked questions.
            </h2>
            <p className="mt-4 text-sm text-muted">Everything you need to know before getting started.</p>
            <p className="mt-6 text-sm">
              Still have questions?{" "}
              <Link href="/book" className="font-medium">
                Talk to our team →
              </Link>
            </p>
          </div>
          <FaqList />
        </Container>
      </section>

      <section className="sky-photo py-24">
        <Container className="text-center">
          <p className="text-[11px] font-semibold tracking-[0.16em] text-ink/45">READY TO LAUNCH?</p>
          <h2 className="display mx-auto mt-4 max-w-2xl text-[44px] sm:text-[52px]">
            Your next creator
            <br />
            campaign starts here.
          </h2>
          <p className="mx-auto mt-4 max-w-lg text-[16px] text-ink/60">
            Get a clear creator strategy, campaign format and estimated budget for your next launch.
          </p>
          <div className="mx-auto mt-10 max-w-lg rounded-[32px] bg-white p-8 text-left shadow-[0_30px_80px_-48px_rgb(23_24_28/0.45)]">
            <div className="flex items-center gap-3">
              <img src="/lp/avatar-h.png" alt="" className="size-10 rounded-full object-cover" />
              <p className="text-[11px] font-semibold tracking-[0.16em] text-brand">CAMPAIGN STRATEGY CALL</p>
            </div>
            <h3 className="mt-5 text-[28px] font-semibold">30-minute working session</h3>
            <p className="mt-2 text-sm text-muted">Leave with a concrete plan for your next creator campaign.</p>
            <ul className="mt-6 divide-y divide-border text-[15px]">
              {["Creator strategy", "Campaign format", "Budget recommendation"].map((item) => (
                <li key={item} className="flex items-center gap-2 py-3">
                  <span className="size-1.5 rounded-full bg-brand" /> {item}
                </li>
              ))}
            </ul>
            <ButtonLink href="/book" size="lg" className="mt-6 h-12 w-full bg-[#17181C]">
              Book a campaign call <ArrowRight className="size-4" />
            </ButtonLink>
            <p className="mt-3 text-center text-xs text-muted">Pick a time on the next page.</p>
            <p className="mt-3 text-center text-sm">
              Prefer to start yourself?{" "}
              <Link href="/register" className="font-medium">
                Start for free →
              </Link>
            </p>
          </div>
          <p className="mt-10 text-sm text-ink/45">Trusted by B2B teams building creator-led acquisition.</p>
        </Container>
      </section>
    </>
  );
}
